services:
  backend:
    container_name: tms-backend
    build: .
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    volumes:
      - public-data:/usr/src/app/public
    networks:
      - proxy

volumes:
  public-data:

networks:
  proxy:

